# Generated by Django 3.2.5 on 2021-12-24 02:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userlog', '0008_auto_20211222_1812'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userlog',
            name='log_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 24, 11, 35, 49, 462959)),
        ),
    ]
