# Generated by Django 3.2.5 on 2021-12-24 02:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routine', '0008_alter_routine_create_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='routine',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 24, 11, 35, 49, 461960)),
        ),
    ]
